#!/usr/bin/python

try:
    import  json
except:
    import simplejson as json
import  os

def prettyprint( f ):
    lines = f.readlines()
    bookmarks = json.loads( "".join(lines) )
    print json.dumps( bookmarks, sort_keys=True, indent=2 )

if __name__ == "__main__":
    import  sys
    ok = True
    argc = len( sys.argv )
    if argc == 1:
        try:
            prettyprint( sys.stdin )
        except:
            ok = False
    else:
        for optarg in sys.argv[ 1: ]:
            if argc > 2:
                print "===> %s\n" % optarg
            f = open( optarg, 'r' )
            prettyprint( f )
            f.close()
            if argc > 2:
                print ""
    exit
